name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

jobs:
  linux:
    name: ${{ matrix.PY }}-pytest
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        PY:
          - "3.12"
          - "3.13"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.PY }}
      - name: Install
        run: |
          pip install ./fsspec-proxy
          pip install ./pyscript-fsspec-client[test]
      - name: test
        run: pytest -v -s
